export const ADD_WALL_POST = 'ADD_WALL_POST';
export const DELETE_WALL_POST = 'DELETE_WALL_POST';
export const SEARCH_WALL_POST = 'SEARCH_WALL_POST';
export const FETCH_FRIENDS = 'FETCH_FRIENDS';
export const REQUESTED_FRIENDS = 'REQUESTED_FRIENDS';
export const REQUESTED_FRIENDS_SUCCEEDED = 'REQUESTED_FRIENDS_SUCCEEDED';
export const REQUESTED_FRIENDS_FAILED = 'REQUESTED_FRIENDS_FAILED';
export const FETCH_PHOTOS = 'FETCH_PHOTOS';
export const REQUESTED_PHOTOS = 'REQUESTED_PHOTOS';
export const REQUESTED_PHOTOS_SUCCEEDED = 'REQUESTED_PHOTOS_SUCCEEDED';
export const REQUESTED_PHOTOS_FAILED = 'REQUESTED_PHOTOS_FAILED';
export const FETCH_NEWS = 'FETCH_NEWS';
export const REQUESTED_NEWS = 'REQUESTED_NEWS';
export const REQUESTED_NEWS_SUCCEEDED = 'REQUESTED_NEWS_SUCCEEDED';
export const REQUESTED_NEWS_FAILED = 'REQUESTED_NEWS_FAILED';
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const SHOW_ALBUM_CAROUSEL = 'SHOW_ALBUM_CAROUSEL';
export const HIDE_ALBUM_CAROUSEL = 'HIDE_ALBUM_CAROUSEL';
export const SHOW_PHOTO_ALBUM = 'SHOW_PHOTO_ALBUM';
export const HIDE_PHOTO_ALBUM = 'HIDE_PHOTO_ALBUM';
export const ADD_PHOTO_COMMENT = 'ADD_PHOTO_COMMENT';
export const DELETE_PHOTO_COMMENT = 'DELETE_PHOTO_COMMENT';
export const SEARCH_FRIENDS = 'SEARCH_FRIENDS';

export default {
	SHOW_PHOTO_ALBUM,
	HIDE_PHOTO_ALBUM,
	SHOW_ALBUM_CAROUSEL,
	HIDE_ALBUM_CAROUSEL,
	SHOW_MODAL,
	HIDE_MODAL,
	ADD_WALL_POST,
	DELETE_WALL_POST,
	SEARCH_WALL_POST,
	FETCH_FRIENDS,
	REQUESTED_FRIENDS,
	REQUESTED_FRIENDS_SUCCEEDED,
	REQUESTED_FRIENDS_FAILED,
	FETCH_PHOTOS,
	REQUESTED_PHOTOS,
	REQUESTED_PHOTOS_SUCCEEDED,
	REQUESTED_PHOTOS_FAILED,
	ADD_PHOTO_COMMENT,
	DELETE_PHOTO_COMMENT,
	FETCH_NEWS,
	REQUESTED_NEWS,
	REQUESTED_NEWS_SUCCEEDED,
	REQUESTED_NEWS_FAILED,
	SEARCH_FRIENDS,
};
