export const ADD_WALL_POST = 'ADD_WALL_POST';
export const DELETE_WALL_POST = 'DELETE_WALL_POST';
export const SEARCH_WALL_POST = 'SEARCH_WALL_POST';

export const FETCH_FREINDS = 'FETCH_FREINDS';
export const REQUESTED_FREINDS = 'REQUESTED_FREINDS';
export const REQUESTED_FREINDS_SUCCEEDED = 'REQUESTED_FREINDS_SUCCEEDED';
export const REQUESTED_FREINDS_FAILED = 'REQUESTED_FREINDS_FAILED';

export const FETCH_PHOTOS = 'FETCH_PHOTOS';
export const REQUESTED_PHOTOS = 'REQUESTED_PHOTOS';
export const REQUESTED_PHOTOS_SUCCEEDED = 'REQUESTED_PHOTOS_SUCCEEDED';
export const REQUESTED_PHOTOS_FAILED = 'REQUESTED_PHOTOS_FAILED';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export default {
	SHOW_MODAL,
	HIDE_MODAL,
	ADD_WALL_POST,
	DELETE_WALL_POST,
	SEARCH_WALL_POST,
	FETCH_FREINDS,
	REQUESTED_FREINDS,
	REQUESTED_FREINDS_SUCCEEDED,
	REQUESTED_FREINDS_FAILED,
	FETCH_PHOTOS,
	REQUESTED_PHOTOS,
	REQUESTED_PHOTOS_SUCCEEDED,
	REQUESTED_PHOTOS_FAILED,
};
